import { Post, Comment } from '../types';

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    username: 'alexm',
    question: 'Is the new iPhone 16 Pro worth the upgrade from iPhone 14?',
    categories: ['Tech', 'Shopping'],
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80'],
    yesCount: 142,
    noCount: 89,
    commentCount: 23,
    createdAt: '2025-04-03T10:30:00Z',
    userVote: null,
  },
  {
    id: '2',
    username: 'sofia_k',
    question: 'Do these sneakers work with a casual office look?',
    categories: ['Fashion'],
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80',
    ],
    yesCount: 78,
    noCount: 12,
    commentCount: 9,
    createdAt: '2025-04-03T09:15:00Z',
    userVote: null,
  },
  {
    id: '3',
    username: 'travel_dan',
    question: 'Is Bali still worth visiting in 2025 given how crowded it has become?',
    categories: ['Travel'],
    yesCount: 201,
    noCount: 98,
    commentCount: 45,
    createdAt: '2025-04-03T08:00:00Z',
    userVote: null,
  },
  {
    id: '4',
    username: 'mikey_r',
    question: 'Is skipping dessert really worth it when dieting?',
    categories: ['Lifestyle', 'Food'],
    yesCount: 55,
    noCount: 134,
    commentCount: 31,
    createdAt: '2025-04-02T22:45:00Z',
    userVote: null,
  },
  {
    id: '5',
    username: 'nina_v',
    question: 'Red flag if someone takes more than 24h to reply to texts?',
    categories: ['Relationships'],
    yesCount: 88,
    noCount: 210,
    commentCount: 67,
    createdAt: '2025-04-02T20:00:00Z',
    userVote: null,
  },
  {
    id: '6',
    username: 'home_guru',
    question: 'Is an air fryer actually worth buying or just another kitchen gadget?',
    categories: ['Home', 'Shopping'],
    images: ['https://images.unsplash.com/photo-1648417782946-14aced01a2db?w=800&q=80'],
    yesCount: 312,
    noCount: 44,
    commentCount: 52,
    createdAt: '2025-04-02T18:30:00Z',
    userVote: null,
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    username: 'techgeek99',
    text: 'The camera improvements alone make it worth it for me.',
    createdAt: '2025-04-03T11:00:00Z',
  },
  {
    id: 'c2',
    username: 'budget_buyer',
    text: 'Unless you really need the camera, save your money.',
    createdAt: '2025-04-03T10:45:00Z',
  },
  {
    id: 'c3',
    username: 'sarah_m',
    text: 'Jumped from 13 Pro and honestly blown away. Do it!',
    createdAt: '2025-04-03T10:20:00Z',
  },
];

export const CATEGORIES = [
  { name: 'Shopping', emoji: '🛍️' },
  { name: 'Tech', emoji: '💻' },
  { name: 'Fashion', emoji: '👗' },
  { name: 'Food', emoji: '🍕' },
  { name: 'Travel', emoji: '✈️' },
  { name: 'Relationships', emoji: '❤️' },
  { name: 'Lifestyle', emoji: '🌿' },
  { name: 'Home', emoji: '🏠' },
  { name: 'Other', emoji: '💬' },
];
